### ISSUE TITLE
[FEATURE] Dealing with 429's?

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#688]
I apologize for marking it as a "feature" because it's more like a discussion topic. Or maybe it sounds like a proposal for a wiki page.

HTTP code 429 is basically DDoS-Guard, right?

What are the typical ways to deal with it?

I have a feeling that it worked slightly better in v4 than in v5. But I have no data to back up this claim with.

I set my rate limiting options to one concurrent download, and I am still hitting a bunch of 429s on bunkr. 

```
Rate_Limiting_Options:
  connection_timeout: 15
  download_attempts: 10
  download_delay: 1
  max_simultaneous_downloads: 1
  max_simultaneous_downloads_per_domain: 1
  rate_limit: 50
  read_timeout: 300
```

Every time I run CDL to download a significantly large forum thread, there's still a bunch of failed downloads with 429. Previously, in v4, all it took was re-launching CDL again (and maybe once again) to download the remaining file. But not anymore. I tried launching CDL four or five times in a row, and there's still about a dozen files being blocked.

I confirm when using the same link in a browser, download starts. So, it's not like it's actually a 404 or 451 disguised as 429 as it sometimes happens with other downloads.

So maybe I'm just getting unlucky, or v5 is somehow more "efficient" (aggressive?) in trying to download stuff from bunkr? Any further tuning recommendations?
