### ISSUE TITLE
[FEATURE] improve robustness of coomer scraping

### ISSUE THREAD

**Issue by baccccccc** [Jules-WinnfieldX/CyberDropDownloader#905]
I wish there was an issue type for “discussion” because this is not even a feature request per se. I guess discord works better for this but I don't use one.

So, I'm trying to download an extermely large coomer profile (`anastasiaxxx89`) which currently shows 193 pages. CDL always tries for a while and then gets a 429 during scrape. I assume it's hammering too hard becasue with the browser, I can still navigate the website.

Usually updating the user agent in CDL and increasing various timeouts and intervals helps, but apparently not in this case. I'm also not in the mood to set up solvrr or other crazy geeky stuff.

What are my other options? I don't mind if it takes a week or a month. I just want the damn thing scraped eventually. Here are my current rate limiting settings.

```
Rate_Limiting_Options:
  connection_timeout: 60
  download_attempts: 5
  download_delay: 20.0
  max_simultaneous_downloads: 1
  max_simultaneous_downloads_per_domain: 1
  rate_limit: 2
  read_timeout: 300
```
